from __future__ import annotations

AI_SCOPE_INSTANCE = "instance"
AI_SCOPE_HOUSEHOLD = "household"
AI_SCOPE_KEY_INSTANCE = "instance"

AI_PROVIDER_OLLAMA = "ollama"
AI_PROVIDER_OPENAI_COMPATIBLE = "openai_compatible"
AI_PROVIDER_TYPES = {
    AI_PROVIDER_OLLAMA,
    AI_PROVIDER_OPENAI_COMPATIBLE,
}

AI_HEALTH_UNKNOWN = "unknown"
AI_HEALTH_HEALTHY = "healthy"
AI_HEALTH_UNHEALTHY = "unhealthy"

AI_SUGGESTION_MEAL = "meal_suggestions"
AI_SUGGESTION_EXPIRY_FIRST = "expiry_first"
AI_SUGGESTION_BUY_EXTRA = "buy_a_few_extra"
AI_SUGGESTION_RECIPE_GAP = "recipe_gap"
AI_SUGGESTION_KINDS = {
    AI_SUGGESTION_MEAL,
    AI_SUGGESTION_EXPIRY_FIRST,
    AI_SUGGESTION_BUY_EXTRA,
    AI_SUGGESTION_RECIPE_GAP,
}
